/**
 * Interop export adapters (SPEC §12bis, Tier D) — emit handoff artifacts from a variant's design
 * intent for external tools. Pure: each adapter takes an {@link ExportContext} and returns the
 * artifact's filename + content; the CLI handles file IO and (for Stitch) loading the vendored
 * `stitch-design-taste` DESIGN.md template.
 */

export type ExportTarget = 'stitch' | 'v0' | 'claude-design';

export const EXPORT_TARGETS: readonly ExportTarget[] = ['stitch', 'v0', 'claude-design'] as const;

export interface ExportContext {
  brief: string;
  dials: { variance: number; motion: number; density: number };
  primary?: string;
  overlay?: string;
  /** Integration scope (component / route / story), if any. */
  target?: string;
  /** Host framework, for v0 / Claude Design handoff. */
  framework?: string;
  /** The vendored `stitch-design-taste/DESIGN.md` template — required for the `stitch` target. */
  designTemplate?: string;
}

export interface ExportArtifact {
  filename: string;
  content: string;
}

export class ExportError extends Error {
  override readonly name = 'ExportError';
}

/** Replace the value cell of a `| **Label** | `N` | …` dial row in the Stitch DESIGN.md table. */
function setDesignDial(md: string, label: string, value: number): string {
  const row = new RegExp(`(\\| \\*\\*${label}\\*\\* \\| )\`[^\`]*\``);
  return row.test(md) ? md.replace(row, `$1\`${String(value)}\``) : md;
}

/** Build the Stitch `DESIGN.md` by patching the skill template's dials from the genome (SPEC §12bis). */
function exportStitch(ctx: ExportContext): ExportArtifact {
  if (ctx.designTemplate === undefined) {
    throw new ExportError('The stitch target requires the stitch-design-taste DESIGN.md template');
  }
  // Map Tiraz dials onto Stitch's Configuration table (Creativity & Variance both track variance).
  let md = ctx.designTemplate;
  md = setDesignDial(md, 'Creativity', ctx.dials.variance);
  md = setDesignDial(md, 'Variance', ctx.dials.variance);
  md = setDesignDial(md, 'Density', ctx.dials.density);
  md = setDesignDial(md, 'Motion Intent', ctx.dials.motion);

  const overlay =
    ctx.overlay !== undefined && ctx.overlay !== 'none' ? ` · overlay: ${ctx.overlay}` : '';
  const header = [
    '<!-- Generated by Tiraz `export --target stitch` -->',
    '## Project Brief',
    ctx.brief.trim() === '' ? '_(no brief supplied)_' : ctx.brief.trim(),
    '',
    `**Design direction:** ${ctx.primary ?? 'impeccable'}${overlay} · dials variance ${String(ctx.dials.variance)} / motion ${String(ctx.dials.motion)} / density ${String(ctx.dials.density)}.`,
    '',
    '---',
    '',
  ].join('\n');

  return { filename: 'DESIGN.md', content: `${header}${md}` };
}

/** A v0-ready prompt (the `--next` scaffold makes v0 output paste-compatible, SPEC §12bis). */
function exportV0(ctx: ExportContext): ExportArtifact {
  const lines = [
    '# v0 prompt',
    '',
    'Build the following as a React component for Next.js + Tailwind CSS + shadcn/ui.',
    '',
    '## Brief',
    ctx.brief.trim() === '' ? '(describe the component to build)' : ctx.brief.trim(),
    '',
    '## Design direction',
    `- Taste: ${ctx.primary ?? 'impeccable'}${ctx.overlay !== undefined && ctx.overlay !== 'none' ? ` + ${ctx.overlay} overlay` : ''}`,
    `- Variance (distance from conventional): ${String(ctx.dials.variance)}/10`,
    `- Motion (animation intensity): ${String(ctx.dials.motion)}/10`,
    `- Density (information density): ${String(ctx.dials.density)}/10`,
    '- No generic AI defaults: customize radii, color, shadow, type. Avoid the "AI purple" aesthetic.',
  ];
  if (ctx.target !== undefined) {
    lines.push('', `## Scope`, ctx.target);
  }
  lines.push('');
  return { filename: 'v0-prompt.md', content: lines.join('\n') };
}

/** A codebase-aware handoff brief for Claude Design (reads real components, SPEC §12bis). */
function exportClaudeDesign(ctx: ExportContext): ExportArtifact {
  const lines = [
    '# Claude Design handoff',
    '',
    'Codebase-aware exploration: read the repo’s real components and design tokens, then build',
    'within them (integration-first — do not impose a new stack).',
    '',
    '## Brief',
    ctx.brief.trim() === '' ? '(describe the section to design)' : ctx.brief.trim(),
    '',
    '## Context',
    `- Framework: ${ctx.framework ?? '(detect from the repo)'}`,
    `- Taste: ${ctx.primary ?? 'redesign-existing-projects'}${ctx.overlay !== undefined && ctx.overlay !== 'none' ? ` + ${ctx.overlay} overlay` : ''}`,
    `- Dials — variance ${String(ctx.dials.variance)} / motion ${String(ctx.dials.motion)} / density ${String(ctx.dials.density)} (1–10).`,
  ];
  if (ctx.target !== undefined) {
    lines.push(`- Scope: ${ctx.target}`);
  }
  lines.push(
    '',
    'Reuse existing tokens and components; match the established system rather than inventing values.',
    '',
  );
  return { filename: 'claude-design-brief.md', content: lines.join('\n') };
}

/** Emit a handoff artifact for the given interop target (SPEC §12bis). */
export function exportArtifact(target: ExportTarget, ctx: ExportContext): ExportArtifact {
  switch (target) {
    case 'stitch':
      return exportStitch(ctx);
    case 'v0':
      return exportV0(ctx);
    case 'claude-design':
      return exportClaudeDesign(ctx);
  }
}
